## Importing Libs

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests 
from bs4 import BeautifulSoup
import json
from pprint import pprint
import matplotlib.image as mpimg
import matplotlib.patches as patches
from PIL import Image
from io import BytesIO
import highlight_text
import matplotlib as mpl
from matplotlib.gridspec import GridSpec
from mplsoccer import Pitch, VerticalPitch
import matplotlib.image as mpimg
import matplotlib.patches as patches
from PIL import Image
from io import BytesIO
from mplsoccer import PyPizza, add_image, FontManager
from matplotlib.patches import Rectangle
import matplotlib.font_manager as font_manager
import matplotlib.image as mpimg
import matplotlib.patches as patches
from PIL import Image
from io import BytesIO
from mplsoccer import PyPizza, add_image, FontManager
#import soccerdata as sd
import re
from unidecode import unidecode
from scipy.spatial import ConvexHull
from matplotlib.colors import LinearSegmentedColormap
from highlight_text import ax_text, fig_text
import matplotlib.patheffects as path_effects
from scipy.ndimage import gaussian_filter
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.patheffects as path_effects


from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import main
import visuals
import seaborn as sns
import requests
import utils
import os
%load_ext autoreload
%autoreload 2

pd.set_option("display.max_rows", None, "display.max_columns", None)
#background = "#010b14"
background = "white"
text_color = 'black'
primary = '#C8102E'
secondary = 'lightblue'
mpl.rcParams['xtick.color'] = text_color
mpl.rcParams['ytick.color'] = text_color

In [2]:
import matplotlib.font_manager as fm
from mplsoccer import FontManager

# Set the path to the locally downloaded font file
font_path = r'C:\Users\acer\Documents\GitHub\IndianCitizen\ScorePredict\Score Logos-20241022T100701Z-001\Score Logos\Sora_Font\Sora-Regular.ttf'

# Add the font to matplotlib
font_prop = fm.FontProperties(fname=font_path)

# You can now use this font in your plots
fm_sora = FontManager()
#fm_sora.prop = font_prop

print("Font loaded and registered successfully!")

Font loaded and registered successfully!

## Data Extraction

### WhoScored

In [3]:
import glob
import os
import pandas as pd
root_folder = "D:/Scrape-Whoscored-Event-Data/data/"
exclude_folders = [
    os.path.join(root_folder, "champions-league").replace("\\", "/"),
    os.path.join(root_folder, "eredivise").replace("\\", "/"),
    os.path.join(root_folder, "fa-cup").replace("\\", "/"),
]

# Get all CSV files recursively
csv_files = glob.glob(os.path.join(root_folder, "**", "*.csv"), recursive=True)

# Normalize file paths and filter out excluded folders
csv_files = [
    f for f in csv_files
    if not any(f.replace("\\", "/").startswith(excluded) for excluded in exclude_folders)
]

# List to hold the DataFrames
dataframes = []

# Loop through the CSV files and read them into DataFrames
for file in csv_files:
    print(f"Reading: {file}")
    dfi = pd.read_csv(file)
    dataframes.append(dfi)

# Merge if files were found
if dataframes:
    df = pd.concat(dataframes, ignore_index=True)
    print("All CSV files successfully merged into a single DataFrame.")
else:
    print("No CSV files found in the specified directory.")

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events1.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events4.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-03-19.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-01.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-09.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-16.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-22.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-29.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-05-12.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\eredivisie\eredivisie_events_2025-04-02.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (31,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\eredivisie\eredivisie_events_2025-04-02_2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (36,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\eredivisie\eredivisie_events_2025-04-02_3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events4.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events5.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events6.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-03-19.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-01.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-09.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-16.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-22.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-05-01.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-05-12.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-01.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-09.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-16.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-23.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-05-12.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue1_events1.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_12948\3813253844.py:26: DtypeWarning: Columns (35,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue1_events2.csv

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [3]:
import glob
import os
import pandas as pd

# Specify the root directory containing all subfolders
root_folder = "D:/Scrape-Whoscored-Event-Data/data/"

# Use glob to get all CSV file paths recursively from subdirectories
csv_files = glob.glob(os.path.join(root_folder, "**", "*.csv"), recursive=True)

# List to hold the DataFrames
dataframes = []

# Loop through the CSV files and read them into DataFrames
for file in csv_files:
    print(f"Reading: {file}")
    dfi = pd.read_csv(file)  # Read the CSV file
    dataframes.append(dfi)   # Append the DataFrame to the list

# Check if any CSV files were found
if dataframes:
    # Concatenate all DataFrames into a single DataFrame
    df = pd.concat(dataframes, ignore_index=True)
    print("All CSV files successfully merged into a single DataFrame.")
else:
    print("No CSV files found in the specified directory.")

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events1.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events4.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-03-19.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-01.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-09.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-16.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-22.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-04-29.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\bundesliga\bundesliga_events_2025-05-12.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\champions-league\champions-league_events_2025-04-17.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\champions-league\champions-league_events_2025-05-01.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\champions-league\ucl_events1.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (22,36,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\eredivisie\eredivisie_events_2025-04-02.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (31,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\eredivisie\eredivisie_events_2025-04-02_2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (36,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\eredivisie\eredivisie_events_2025-04-02_3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\europa-league\europa-league_events_2025-05-18.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (22,36,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\fa-cup\fa-cup_events_2025-05-13.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\fa-cup\fa-cup_events_2025-05-13_2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events4.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events5.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events6.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-03-19.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-01.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-09.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-16.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-04-22.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-05-01.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\laliga\laliga_events_2025-05-12.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-01.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-09.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-16.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-04-23.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue-1_events_2025-05-12.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue1_events1.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (35,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue1_events2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue1_events3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue1_events4.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\ligue-1\ligue1_events_2025-03-18.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\pl_events1.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\pl_events2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\pl_events3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\pl_events4.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-03-18.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (36,38,40) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-04-04.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-04-09.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-04-14.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-04-16.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-04-22.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-04-25.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-04-29.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\premier-league\premier-league_events_2025-05-12.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serie-a_events_2025-03-19.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serie-a_events_2025-04-01.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serie-a_events_2025-04-09.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serie-a_events_2025-04-16.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serie-a_events_2025-04-23.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serie-a_events_2025-05-07.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (39,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serieA_events1.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serieA_events2.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serieA_events3.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (37,259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serieA_events4.csv
Reading: D:/Scrape-Whoscored-Event-Data/data\serie-a\serieA_events5.csv

C:\Users\acer\AppData\Local\Temp\ipykernel_17096\430360680.py:17: DtypeWarning: Columns (259) have mixed types. Specify dtype option on import or set low_memory=False.
  dfi = pd.read_csv(file)  # Read the CSV file

All CSV files successfully merged into a single DataFrame.

In [4]:
teams_dict = {
    65: 'Barcelona',
    63: 'Atletico Madrid',
    52: 'Real Madrid',
    53: 'Atletic Club',
    839: 'Villarreal',
    54: 'Real Betis',
    64: 'Rayo Vallecano',
    51: 'Mallorca',
    68: 'Real Sociedad',
    62: 'Celta Vigo',
    131: 'Osasuna',
    67: 'Sevilla',
    2783: 'Girona',
    819: 'Getafe',
    70: 'Espanyol',
    825: 'Leganes',
    838: 'Las Palmas',
    55 : 'Valencia',
    60 : 'Deportivo Alaves',
    58: 'Real Valladolid',
    13: 'Arsenal',
    161: 'Wolves',
    24: 'Aston Villa',
    211: 'Brighton',
    30: 'Tottenham',
    167: 'Man City',
    14: 'Leicester',
    18: 'Southampton',
    183: 'Bournemouth',
    26: 'Liverpool',
    23: 'Newcastle',
    15: 'Chelsea',
    174: 'Nottingham Forest',
    29: 'West Ham',
    32: 'Man Utd',
    170: 'Fulham',
    189: 'Brentford',
    162: 'Crystal Palace',
    31: 'Everton',
    165: 'Ipswich',
    37: 'Bayern Munich',
    36: 'Bayer Leverkusen',
    45: 'Eintracht Frankfurt',
    219: 'Mainz 05',
    50: 'Freiburg',
    7614: 'RB Leipzig',
    33: 'Wolfsburg',
    134: 'Borussia M.Gladbach',
    41: 'VfB Stuttgart',
    44: 'Borussia Dortmund',
    1730: 'Augsburg',
    42: 'Werder Bremen',
    1211: 'Hoffenheim',
    796: 'Union Berlin',
    283: 'St. Pauli',
    1206: 'Holstein Kiel',
    4852: 'FC Heidenheim',
    109: 'Bochum',
    75 : 'Inter',
    276 : 'Napoli',
    300 : 'Atalanta',
    87 : 'Juventus',
    77 : 'Lazio',
    71 : 'Bologna',
    73 : 'Fiorentina',
    84 : 'Roma',
    80 : 'AC Milan',
    86 : 'Udinese',
    72 : 'Torino',
    278 : 'Genoa',
    1290 : 'Como',
    76 : 'Verona',
    78 : 'Cagliari',
    79 : 'Lecce',
    24341 : 'Parma Calcio',
    272 : 'Empoli',
    85 : 'Venezia',
    269 : 'Monza',
    304 : 'PSG',
    249 : 'Marseille',
    613 : 'Nice',
    248 : 'Monaco',
    607 : 'Lille',
    228 : 'Lyon',
    148 : 'Strasbourg',
    246 : 'Toulouse',
    309 : 'Lens',
    2332 : 'Brest',
    313 : 'Rennes',
    308 : 'Auxerre',
    614 : 'Angers',
    302 : 'Nantes',
    950 : 'Reims',
    217 : 'Le Havre',
    145 : 'Saint-Etienne',
    311 : 'Montpellier',
    299 : 'Benfica',
    129 : 'PSV',
    130 : 'Ajax',
    256: 'Feyenoord',
    128 : 'Utrecht',
    243 : 'AZ-Alkmaar',
    113 : 'Twente',
    874 : 'Go Ahead Eagles',
    758 : 'FC Groningen',
    242 : 'Fortuna Sittard',
    870 : 'Heracles',
    287 : 'SC Heerenveen',
    116 : 'NEC Nijmegen',
    783 : 'NAC Breda',
    868 : 'PEC Zwolle',
    303 : 'Sparta Rotterdam',
    115 : 'Willem II',
    114 : 'RKC Waalwijk',
    1347 : 'Almere City'
}

# temprary use of typeId of period column
df['period'] = df['period'].replace({'FirstHalf': 1, 'SecondHalf': 2, 'FirstPeriodOfExtraTime': 3, 'SecondPeriodOfExtraTime': 4,
                                     'PenaltyShootout': 5, 'PostGame': 14, 'PreMatch': 16})
# new column for cumulative minutes, This part is taken from the "jakeyk11.github.io" github repository and modified for my use
def cumulative_match_mins(events_df):
    events_out = pd.DataFrame()
    # Add cumulative time to events data, resetting for each unique match
    match_events = events_df.copy()
    match_events['cumulative_mins'] = match_events['minute'] + (1/60) * match_events['second']
    # Add time increment to cumulative minutes based on period of game.
    for period in np.arange(1, match_events['period'].max() + 1, 1):
        if period > 1:
            t_delta = match_events[match_events['period'] == period - 1]['cumulative_mins'].max() - \
                                   match_events[match_events['period'] == period]['cumulative_mins'].min()
        elif period == 1 or period == 5:
            t_delta = 0
        else:
            t_delta = 0
        match_events.loc[match_events['period'] == period, 'cumulative_mins'] += t_delta
    # Rebuild events dataframe
    events_out = pd.concat([events_out, match_events])
    return events_out

df = cumulative_match_mins(df)

df = df.reset_index(drop=True)
df['index'] = range(1, len(df) + 1)
df = df[['index'] + [col for col in df.columns if col != 'index']]

df = df.sort_values(by='matchId')

# New Column for Team Names and Oppositon TeamNames
df['teamName'] = df['teamId'].map(teams_dict)
team_names = list(teams_dict.values())
#opposition_dict = {team_names[i]: team_names[1-i] for i in range(len(team_names))}
#df['oppositionTeamName'] = df['teamName'].map(opposition_dict)

# Reshaping the data from 100x100 to 105x68, as I use the pitch_type='uefa', in the pitch function, you can consider according to your use
df['x'] = df['x']*1.05
df['y'] = df['y']*0.68
df['endX'] = df['endX']*1.05
df['endY'] = df['endY']*0.68
df['goalMouthY'] = df['goalMouthY']*0.68

df['qualifiers'] = df['qualifiers'].astype(str)
# Calculating passing distance, to find out progressive pass, this will just show the distance reduced by a pass, then will be able to filter passes which has reduced distance value more than 10yds as a progressive pass
df['prog_pass'] = np.where((df['type'] == 'Pass'),
                           np.sqrt((105 - df['x'])**2 + (34 - df['y'])**2) - np.sqrt((105 - df['endX'])**2 + (34 - df['endY'])**2), 0)
# Calculating carrying distance, to find out progressive carry, this will just show the distance reduced by a carry, then will be able to filter carries which has reduced distance value more than 10yds as a progressive carry
#df['prog_carry'] = np.where((df['type'] == 'Carry'),
#                            np.sqrt((105 - df['x'])**2 + (34 - df['y'])**2) - np.sqrt((105 - df['endX'])**2 + (34 - df['endY'])**2), 0)
df['pass_or_carry_angle'] = np.degrees(np.arctan2(df['endY'] - df['y'], df['endX'] - df['x']))

# Making all the alphabets in the name as English Alphabets only (for example: Á will be replaced by A)
df['playerName'] = df['playerName'].astype(str)
df['playerName'] = df['playerName'].apply(unidecode)

# Function to extract short names
def get_short_name(full_name):
    if pd.isna(full_name):
        return full_name
    parts = full_name.split()
    if len(parts) == 1:
        return full_name  # No need for short name if there's only one word
    elif len(parts) == 2:
        return parts[0][0] + ". " + parts[1]
    else:
        return parts[0][0] + ". " + parts[1][0] + ". " + " ".join(parts[2:])

# Applying the function to create 'shortName' column
df['shortName'] = df['playerName'].apply(get_short_name)

df['qualifiers'] = df['qualifiers'].astype(str)
columns_to_drop2 = ['id']
df.drop(columns=columns_to_drop2, inplace=True)

df['period'] = df['period'].replace({1: 'FirstHalf', 2: 'SecondHalf', 3: 'FirstPeriodOfExtraTime', 4: 'SecondPeriodOfExtraTime',
                                     5: 'PenaltyShootout', 14: 'PostGame', 16: 'PreMatch'})

## Data Transformation

### WhoScored

In [6]:
print(list(df.columns))

['index', 'Unnamed: 0', 'eventId', 'minute', 'second', 'teamId', 'h_a', 'x', 'y', 'expandedMinute', 'period', 'type', 'outcomeType', 'qualifiers', 'satisfiedEventsTypes', 'isTouch', 'matchId', 'startDate', 'startTime', 'score', 'ftScore', 'htScore', 'etScore', 'venueName', 'maxMinute', 'playerId', 'playerName', 'endX', 'endY', 'goalMouthZ', 'goalMouthY', 'isShot', 'relatedEventId', 'relatedPlayerId', 'blockedX', 'blockedY', 'isGoal', 'cardType', 'shotBodyType', 'situation', 'shotSixYardBox', 'shotPenaltyArea', 'shotOboxTotal', 'shotOpenPlay', 'shotCounter', 'shotSetPiece', 'shotDirectCorner', 'shotOffTarget', 'shotOnPost', 'shotOnTarget', 'shotsTotal', 'shotBlocked', 'shotRightFoot', 'shotLeftFoot', 'shotHead', 'shotObp', 'goalSixYardBox', 'goalPenaltyArea', 'goalObox', 'goalOpenPlay', 'goalCounter', 'goalSetPiece', 'penaltyScored', 'goalOwn', 'goalNormal', 'goalRightFoot', 'goalLeftFoot', 'goalHead', 'goalObp', 'shortPassInaccurate', 'shortPassAccurate', 'passCorner', 'passCornerAccurate', 'passCornerInaccurate', 'passFreekick', 'passBack', 'passForward', 'passLeft', 'passRight', 'keyPassLong', 'keyPassShort', 'keyPassCross', 'keyPassCorner', 'keyPassThroughball', 'keyPassFreekick', 'keyPassThrowin', 'keyPassOther', 'assistCross', 'assistCorner', 'assistThroughball', 'assistFreekick', 'assistThrowin', 'assistOther', 'dribbleLost', 'dribbleWon', 'challengeLost', 'interceptionWon', 'clearanceHead', 'outfielderBlock', 'passCrossBlockedDefensive', 'outfielderBlockedPass', 'offsideGiven', 'offsideProvoked', 'foulGiven', 'foulCommitted', 'yellowCard', 'voidYellowCard', 'secondYellow', 'redCard', 'turnover', 'dispossessed', 'saveLowLeft', 'saveHighLeft', 'saveLowCentre', 'saveHighCentre', 'saveLowRight', 'saveHighRight', 'saveHands', 'saveFeet', 'saveObp', 'saveSixYardBox', 'savePenaltyArea', 'saveObox', 'keeperDivingSave', 'standingSave', 'closeMissHigh', 'closeMissHighLeft', 'closeMissHighRight', 'closeMissLeft', 'closeMissRight', 'shotOffTargetInsideBox', 'touches', 'assist', 'ballRecovery', 'clearanceEffective', 'clearanceTotal', 'clearanceOffTheLine', 'dribbleLastman', 'errorLeadsToGoal', 'errorLeadsToShot', 'intentionalAssist', 'interceptionAll', 'interceptionIntheBox', 'keeperClaimHighLost', 'keeperClaimHighWon', 'keeperClaimLost', 'keeperClaimWon', 'keeperOneToOneWon', 'parriedDanger', 'parriedSafe', 'collected', 'keeperPenaltySaved', 'keeperSaveInTheBox', 'keeperSaveTotal', 'keeperSmother', 'keeperSweeperLost', 'keeperMissed', 'passAccurate', 'passBackZoneInaccurate', 'passForwardZoneAccurate', 'passInaccurate', 'passAccuracy', 'cornerAwarded', 'passKey', 'passChipped', 'passCrossAccurate', 'passCrossInaccurate', 'passLongBallAccurate', 'passLongBallInaccurate', 'passThroughBallAccurate', 'passThroughBallInaccurate', 'passThroughBallInacurate', 'passFreekickAccurate', 'passFreekickInaccurate', 'penaltyConceded', 'penaltyMissed', 'penaltyWon', 'passRightFoot', 'passLeftFoot', 'passHead', 'sixYardBlock', 'tackleLastMan', 'tackleLost', 'tackleWon', 'cleanSheetGK', 'cleanSheetDL', 'cleanSheetDC', 'cleanSheetDR', 'cleanSheetDML', 'cleanSheetDMC', 'cleanSheetDMR', 'cleanSheetML', 'cleanSheetMC', 'cleanSheetMR', 'cleanSheetAML', 'cleanSheetAMC', 'cleanSheetAMR', 'cleanSheetFWL', 'cleanSheetFW', 'cleanSheetFWR', 'cleanSheetSub', 'goalConcededByTeamGK', 'goalConcededByTeamDL', 'goalConcededByTeamDC', 'goalConcededByTeamDR', 'goalConcededByTeamDML', 'goalConcededByTeamDMC', 'goalConcededByTeamDMR', 'goalConcededByTeamML', 'goalConcededByTeamMC', 'goalConcededByTeamMR', 'goalConcededByTeamAML', 'goalConcededByTeamAMC', 'goalConcededByTeamAMR', 'goalConcededByTeamFWL', 'goalConcededByTeamFW', 'goalConcededByTeamFWR', 'goalConcededByTeamSub', 'goalConcededOutsideBoxGoalkeeper', 'goalScoredByTeamGK', 'goalScoredByTeamDL', 'goalScoredByTeamDC', 'goalScoredByTeamDR', 'goalScoredByTeamDML', 'goalScoredByTeamDMC', 'goalScoredByTeamDMR', 'goalScoredByTeamML', 'goalScoredByTeamMC', 'goalScoredByTeamMR', 'goalScoredByTeamAML', 'goalScoredByTeamAMC', 'goalScoredByTeamAMR', 'goalScoredByTeamFWL', 'goalScoredByTeamFW', 'goalScoredByTeamFWR', 'goalScoredByTeamSub', 'aerialSuccess', 'duelAerialWon', 'duelAerialLost', 'offensiveDuel', 'defensiveDuel', 'bigChanceMissed', 'bigChanceScored', 'bigChanceCreated', 'overrun', 'successfulFinalThirdPasses', 'punches', 'penaltyShootoutScored', 'penaltyShootoutMissedOffTarget', 'penaltyShootoutSaved', 'penaltyShootoutSavedGK', 'penaltyShootoutConcededGK', 'throwIn', 'subOn', 'subOff', 'defensiveThird', 'midThird', 'finalThird', 'pos', 'isOwnGoal', 'cumulative_mins', 'teamName', 'prog_pass', 'pass_or_carry_angle', 'shortName']

In [8]:
shots_df = df[df['type'].isin(['SavedShot', 'MissedShot', 'ShotOnPost', 'Goal'])]
shots_df['isGoal'] = (shots_df['type'] == 'Goal').astype(int)
goal_x, goal_y = 105, 34
shots_df['shot_distance'] = np.sqrt((goal_x - shots_df['x'])**2 + (goal_y - shots_df['y'])**2)

def calculate_angle(x, y):
    goal_width = 7.32
    goal_left = 34 - goal_width / 2
    goal_right = 34 + goal_width / 2
    
    a = np.sqrt((105 - x)**2 + (goal_left - y)**2)
    b = np.sqrt((105 - x)**2 + (goal_right - y)**2)
    c = goal_width

    # Law of Cosines
    angle = np.arccos((a**2 + b**2 - c**2) / (2 * a * b))
    return angle

shots_df['shot_angle'] = shots_df.apply(lambda row: calculate_angle(row['x'], row['y']), axis=1)
shots_df = shots_df.copy()
shots_df['shotBodyType'] = shots_df['shotBodyType'].fillna('Unknown')
shots_df = pd.get_dummies(shots_df, columns=['shotBodyType'], drop_first=True)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Features
features = ['shot_distance', 'shot_angle', 'shotOpenPlay', 'shotCounter', 'shotSetPiece', 'shotDirectCorner'] + \
           [col for col in shots_df.columns if col.startswith('shotBodyType_')]

X = shots_df[features]
y = shots_df['isGoal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Evaluation
y_pred = model.predict_proba(X_test)[:, 1]
print("ROC AUC Score:", roc_auc_score(y_test, y_pred))

ROC AUC Score: 0.7762334253765684

In [13]:
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

xgb_model = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    random_state=42
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [14]:
# Predict probabilities (xG)
shots_df['xG'] = xgb_model.predict_proba(X)[:, 1]

# Evaluate
y_pred = xgb_model.predict_proba(X_test)[:, 1]
roc_score = roc_auc_score(y_test, y_pred)
print(f"ROC AUC Score: {roc_score:.4f}")

ROC AUC Score: 0.7789

In [15]:
import joblib
joblib.dump(xgb_model, 'xgboost_xg_model.pkl')

['xgboost_xg_model.pkl']

In [10]:
shots_df['xG'] = model.predict_proba(X)[:, 1]

In [19]:
# Group by player and sum xG
top_xg_players = shots_df.groupby('playerName')['xG'].sum().sort_values(ascending=False).head(10).reset_index()

# Rename columns for clarity
top_xg_players.columns = ['Player', 'Total_xG']

In [20]:
top_xg_players

               Player   Total_xG
0  Robert Lewandowski  32.882488
1     Serhou Guirassy  31.083927
2      Erling Haaland  30.849985
3          Harry Kane  30.822947
4       Kylian Mbappe  28.142342
5       Mohamed Salah  25.889843
6      Jonathan David  22.009695
7        Hugo Ekitike  21.922468
8     Ousmane Dembele  19.637627
9      Alexander Isak  18.774195

In [25]:
# Filter non-goal shots
high_xg_missed = shots_df[shots_df['isGoal'] == 0]

# Sort by xG descending and take top 10
top_missed_xg = high_xg_missed.sort_values(by='xG', ascending=False).head(10)

# Select key columns for display
columns_to_show = ['playerName','startDate','situation', 'minute', 'xG', 'type', 'shot_distance', 'shot_angle']
top_missed_xg_display = top_missed_xg[columns_to_show].reset_index(drop=True)

In [26]:
top_missed_xg_display

,playerName,startDate,situation,minute,xG,type,shot_distance,shot_angle
0,Kike Garcia,2024-11-30T00:00:00,OpenPlay,29,0.971798,SavedShot,65.166091,0.099530
1,Kevin De Bruyne,2024-12-15T00:00:00,OpenPlay,42,0.971798,SavedShot,39.751888,0.110413
2,Amine Gouiri,2025-04-19T00:00:00,OpenPlay,59,0.911086,SavedShot,1.949019,2.177268
3,Makan Aiko,2024-08-16T00:00:00,OpenPlay,50,0.911086,SavedShot,2.564562,1.924864
4,Jorgen Strand Larsen,2025-01-06T00:00:00,OpenPlay,13,0.897005,SavedShot,2.952556,1.784838
5,Noni Madueke,2025-05-04T00:00:00,OpenPlay,55,0.897005,SavedShot,3.185761,1.710675
6,Maroan Sannadi,2025-02-23T00:00:00,OpenPlay,19,0.891463,SavedShot,1.999630,2.142578
7,Kingsley Ehizibue,2025-01-11T00:00:00,OpenPlay,44,0.891463,SavedShot,1.714060,2.275509
8,Morten Thorsby,2025-01-05T00:00:00,OpenPlay,42,0.891463,ShotOnPost,1.796619,2.232085
9,Santiago Gimenez,2024-12-22T00:00:00,OpenPlay,40,0.882202,ShotOnPost,2.955068,2.074832

In [27]:
# Filter non-goal shots
high_xg_missed = shots_df[shots_df['isGoal'] == 1]

# Sort by xG descending and take top 10
top_scored_xg = high_xg_missed.sort_values(by='xG', ascending=True).head(10)

# Select key columns for display
columns_to_show = ['playerName','startDate','situation', 'minute', 'xG', 'type', 'shot_distance', 'shot_angle']
top_scored_xg_display = top_scored_xg[columns_to_show].reset_index(drop=True)

In [28]:
top_scored_xg_display

,playerName,startDate,situation,minute,xG,type,shot_distance,shot_angle
0,Ollie Watkins,2025-03-08T00:00:00,NaN,48,0.018147,Goal,19.899731,0.232750
1,Bryan Cristante,2024-09-29T00:00:00,OpenPlay,74,0.019697,Goal,32.725372,0.219523
2,Raphinha,2025-01-21T00:00:00,OpenPlay,63,0.025886,Goal,27.103477,0.264357
3,Moise Kean,2025-02-06T00:00:00,OpenPlay,88,0.026583,Goal,33.539947,0.210501
4,Wilfried Singo,2024-10-22T00:00:00,OpenPlay,53,0.026583,Goal,33.052669,0.209834
5,Phillip Tietz,2024-11-02T00:00:00,OpenPlay,33,0.026663,Goal,19.234746,0.212300
6,Beto,2025-05-10T00:00:00,NaN,73,0.027978,Goal,23.521716,0.245510
7,Andrea Pinamonti,2024-10-19T00:00:00,SetPiece,84,0.028265,Goal,15.399544,0.462116
8,Christian Kabasele,2024-09-28T00:00:00,FromCorner,34,0.028754,Goal,14.223713,0.492832
9,Igor Paixao,2025-02-12T00:00:00,OpenPlay,2,0.029574,Goal,23.798582,0.206877